services:
  cypress:
    build: .
    volumes:
      - .:/app
      # To avoid mounting node_modules from host (if they exist)
      - /app/node_modules
    environment:
      - CYPRESS_baseUrl=https://the-internet.herokuapp.com/
    command: npx cypress run
